-- Change the DOCUMENT_NUMBER of the EPS_PROPOSAL_BUDGET_EXT table to be a VARCHAR2(40,0).
-- If there is data in EPS_PROPOSAL_BUDGET_EXT, this script keeps it intact.
-- This script can be run repeatedly with no side effects.

ALTER TABLE EPS_PROPOSAL_BUDGET_EXT ADD DOCUMENT_NUMBER2 VARCHAR2(40);
UPDATE EPS_PROPOSAL_BUDGET_EXT SET DOCUMENT_NUMBER2 = to_char(DOCUMENT_NUMBER);
ALTER TABLE EPS_PROPOSAL_BUDGET_EXT DROP COLUMN DOCUMENT_NUMBER;
ALTER TABLE EPS_PROPOSAL_BUDGET_EXT RENAME COLUMN DOCUMENT_NUMBER2 TO DOCUMENT_NUMBER;

