-- Change the PROPOSAL_ID of the AWARD_FUNDING_PROPOSALS table to be a NUMBER(12,0).
--
-- If there is data in AWARD_FUNDING_PROPOSALS, this script keeps it intact, but
-- truncates if the original column is NUMBER(>12,0).
--
-- This script can be run repeatedly with no side effects.

ALTER TABLE AWARD_FUNDING_PROPOSALS ADD PROPOSAL_ID2 NUMBER(12,0);

UPDATE AWARD_FUNDING_PROPOSALS SET PROPOSAL_ID2 = PROPOSAL_ID;

ALTER TABLE AWARD_FUNDING_PROPOSALS DROP COLUMN PROPOSAL_ID;

ALTER TABLE AWARD_FUNDING_PROPOSALS RENAME COLUMN PROPOSAL_ID2 TO PROPOSAL_ID;
