SET DEFINE OFF;

INSERT INTO KRNS_DOC_HDR_T (DOC_HDR_ID,VER_NBR,FDOC_DESC,ORG_DOC_HDR_ID,TMPL_DOC_HDR_ID,EXPLANATION,OBJ_ID) 
  VALUES (KREW_DOC_HDR_S.nextVal,6,'Grants.gov Preloaded Questionnaire 2',null,null,null,SYS_GUID());

INSERT INTO KRNS_DOC_HDR_T (DOC_HDR_ID,VER_NBR,FDOC_DESC,ORG_DOC_HDR_ID,TMPL_DOC_HDR_ID,EXPLANATION,OBJ_ID) 
  VALUES (KREW_DOC_HDR_S.nextVal,6,'Grants.gov Preloaded Questionnaire 1',null,null,null,SYS_GUID());

INSERT INTO KRNS_DOC_HDR_T (DOC_HDR_ID,VER_NBR,FDOC_DESC,ORG_DOC_HDR_ID,TMPL_DOC_HDR_ID,EXPLANATION,OBJ_ID) 
  VALUES (KREW_DOC_HDR_S.nextVal,6,'Grants.gov Preloaded Questionnaire 3',null,null,null,SYS_GUID());

INSERT INTO KRNS_DOC_HDR_T (DOC_HDR_ID,VER_NBR,FDOC_DESC,ORG_DOC_HDR_ID,TMPL_DOC_HDR_ID,EXPLANATION,OBJ_ID) 
  VALUES (KREW_DOC_HDR_S.nextVal,6,'Grants.gov Preloaded Questionnaire 4',null,null,null,SYS_GUID());

COMMIT;
